name: docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Build and Development Version
        run: |
          echo "BUILD_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "RELEASE_NAME=discomfort-${{ github.ref_name }}-linux" >> $GITHUB_ENV
          echo "IMAGE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
        shell: bash
        if: github.event_name == 'push'

      - name: Setup Build and Release Version
        run: |
          echo "BUILD_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          echo "RELEASE_NAME=discomfort-${{ github.event.release.tag_name }}-linux" >> $GITHUB_ENV
          echo "IMAGE_VERSION=${${{ github.event.release.tag_name }}#v}" >> $GITHUB_ENV
        shell: bash
        if: github.event_name == 'release' && github.event.action == 'published'

      - name: Build the Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t tanis2000/discomfort:"${IMAGE_VERSION}" -t tanis2000/discomfort --build-arg BUILD_VERSION="${BUILD_VERSION}" --push -f ./deploy/docker/Dockerfile .

