name: windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [published]
    
jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Setup Build and Development Version
      run: |
        echo "BUILD_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
        echo "RELEASE_NAME=discomfort-${{ github.ref_name }}-macos" >> $GITHUB_ENV
      shell: bash
      if: github.event_name == 'push'

    - name: Setup Build and Release Version
      run: |
        echo "BUILD_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
        echo "RELEASE_NAME=discomfort-${{ github.event.release.tag_name }}-macos" >> $GITHUB_ENV
      shell: bash
      if: github.event_name == 'release' && github.event.action == 'published'

    - name: Setup Environment
      run: |
        mkdir ${{github.workspace}}/build
        cd ${{github.workspace}}/build
        mkdir ${{ env.RELEASE_NAME }}
        cd ../..

    - name: Build
      run: |
        go env -w CGO_ENABLED=1
        go build -v -ldflags="-X 'discomfort/internal/build.Version=${BUILD_VERSION}' -X 'discomfort/internal/build.User=$(id -u -n)' -X 'discomfort/internal/build.Time=$(date)'" -o ${{github.workspace}}/build/discomfort

    - name: Test
      run: go test -v ./...

    - name: Generate artefacts
      shell: cmd
      run: |
        copy /Y ${{github.workspace}}\build\discomfort ${{github.workspace}}\build\${{ env.RELEASE_NAME }}
        cd build
        7z a ${{ env.RELEASE_NAME }}.zip ${{ env.RELEASE_NAME }}

    - name: Upload artefacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.RELEASE_NAME }}.zip
        path: ${{github.workspace}}\build\${{ env.RELEASE_NAME }}.zip

    - name: Upload artefact to release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{github.workspace}}/build/${{ env.RELEASE_NAME }}.zip
        asset_name: ${{ env.RELEASE_NAME }}.zip
        asset_content_type: application/zip
      if: github.event_name == 'release' && github.event.action == 'published'